(StartDate as date, EndDate as date) as table =>
let
    // Generate list of dates
    Source = List.Dates(
        StartDate, 
        Duration.Days(EndDate - StartDate) + 1, 
        #duration(1,0,0,0)
    ),

    // Convert to table
    ToTable = Table.FromList(Source, Splitter.SplitByNothing(), {"Date"}),

    // Ensure type
    ChangedType = Table.TransformColumnTypes(ToTable, {{"Date", type date}}),

    // Add useful columns
    AddYear = Table.AddColumn(ChangedType, "Year", each Date.Year([Date]), Int64.Type),
    AddMonthNumber = Table.AddColumn(AddYear, "Month Number", each Date.Month([Date]), Int64.Type),
    AddMonthName = Table.AddColumn(AddMonthNumber, "Month Name", each Date.ToText([Date], "MMMM"), type text),
    AddMonthShort = Table.AddColumn(AddMonthName, "Month Short", each Date.ToText([Date], "MMM"), type text),

    AddYearMonth = Table.AddColumn(AddMonthShort, "Year-Month", each Date.ToText([Date], "yyyy-MM"), type text),

    AddQuarter = Table.AddColumn(AddYearMonth, "Quarter", each "Q" & Number.ToText(Date.QuarterOfYear([Date])), type text),

    AddDay = Table.AddColumn(AddQuarter, "Day", each Date.Day([Date]), Int64.Type),
    AddDayOfWeek = Table.AddColumn(AddDay, "Day of Week Number", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
    AddDayName = Table.AddColumn(AddDayOfWeek, "Day Name", each Date.ToText([Date], "dddd"), type text),
    AddDayShort = Table.AddColumn(AddDayName, "Day Short", each Date.ToText([Date], "ddd"), type text),

    AddWeek = Table.AddColumn(AddDayShort, "Week Number", each Date.WeekOfYear([Date]), Int64.Type),

    AddIsWeekend = Table.AddColumn(AddWeek, "Is Weekend", each if Date.DayOfWeek([Date], Day.Monday) >= 5 then true else false, type logical),

    AddStartOfMonth = Table.AddColumn(AddIsWeekend, "Start of Month", each Date.StartOfMonth([Date]), type date),
    AddEndOfMonth = Table.AddColumn(AddStartOfMonth, "End of Month", each Date.EndOfMonth([Date]), type date),

    AddYearSort = Table.AddColumn(AddEndOfMonth, "YearMonthSort", each Date.Year([Date]) * 100 + Date.Month([Date]), Int64.Type)

in
    AddYearSort
